"""initial schema baseline

Revision ID: 415d38c3e466
Revises: 
Create Date: 2026-06-19 16:12:24.186528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415d38c3e466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_application_requests_reference_number', ['reference_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_requests', schema=None) as batch_op:
        batch_op.drop_constraint('uq_application_requests_reference_number', type_='unique')

    # ### end Alembic commands ###
